when:
  - event: push
    branch: master
steps:
  - name: copying file
    image: debian
    commands:
      - |
        echo "appending to file"
        tee user.txt > /dev/null <<EOF
        this is line 1
        this is line 2
        EOF
  - name: reading the file
    image: debian
    commands:
      - cat user.txt
